/**
 * @description       : 
 * @author            : $username  Deloitte
 * @date              : 02-06-2025
 * @group             : ITBA
 * @last modified on  : 02-06-2025
 * @last modified by  : Shubham Raut
**/
public with sharing class Steps_WRP {
    public class CreateStepsWrapper {
        public String competition;
        public String contact;
        public Integer todaysSteps;
        public Integer goldenPoint;
    }
}